### ISSUE TITLE
FIle train_ARRAU_sen.conll is not found

### ISSUE THREAD

**Issue by hienvuhuy** [gorka96/text2cor#1]
I am replicating your result with the ARRAU dataset from LDC. Unfortunately, there is no description of the file **"train_ARRAU_sen.conll"** in the training step.

> python3 word2seq.py data/**train_ARRAU_sen.conll** data/train_ARRAU_seq

I guess it is output after running the command

> python3 mmax2conll.py

The only description of the file ***train_ARRAU_sen.conll*** is in the file "https://github.com/gorka96/text2cor/blob/main/mmax2conll.py" line 63, but it is so hard to make a guess what it is.

Can you give me some hints about this file or show me how to generate it?

Thank you very much.

**Comment by GorkaUrbizu** [comment]
Hi! And thanks for the interest on my work!

I haven't work on this for a while, but you are right, it's the output of the  mmax2conll.py script. I just realized that I have the IO filenames hard-coded (l56-60), but just changing "fout" and "folders" (63-64L) should be enough. 

as you already found it in that script, 
`word \t sen \t cor \n 
`
it would be a file with 3 columns, in the first column the raw text, word by word, the second one the number of the sentence that the word is part of. and the 3rd column the coreference annotation in the conll style. 

something like:

```
this \tab 1 \tab (1) \newline
is \tab 1 \tab _ \newline
my \tab 1 \tab (1|(2) \newline
example \tab 1 \tab 1) \newline
. \tab 1 \tab _ \newline
```

I will search for the files, which I must keep them somewhere. I think that I can't share the whole thing due to the corpus license, but I will share the first few rows so you understand the format.

Gorka

**Comment by GorkaUrbizu** [comment]
Hi again!

I found the files =P I hope these will be helpful, and answer your questions.

There was an issue with some documents on ARRAU which didn't contain punctuation marks, so that's why I extracted the sentence information from the corpus, to be able to keep sentence boundaries for the training instance creation. so train_ARRAU_sen.conll  should have this format:

```
#begin document vpc_0021
Argentina	1	(1)
said	1	_
it	1	(1)
will	1	_
ask	1	_
creditor	1	(4
banks	1	4)
to	1	_
halve	1	_
its	1	(1)|(3
foreign	1	_
debt	1	_
of	1	_
$	1	(7
64	1	_
billion	1	_
the	1	_
in	1	_
the	1	(8
developing	1	_
world	1	3)|7)|8)
.	1	_
The	2	(9
declaration	2	_
by	2	_
Economy	2	(2|(10|(11)
Minister	2	10)
Nestor	2	_
Rapanelli	2	9)|2)
is	2	_
believed	2	_
to	2	_
be	2	_
the	2	(12
first	2	_
time	2	_
such	2	(13
an	2	_
action	2	13)
has	2	_
been	2	_
called	2	_
for	2	_
by	2	_
an	2	(2
Argentine	2	(1)
official	2	_
of	2	_
such	2	(14
stature	2	12)|2)|14)
.	2	_
The	3	(1
Latin	3	(15
American	3	15)
nation	3	1)
has	3	_
paid	3	_
very	3	_
little	3	_
on	3	_
its	3	(1)|(3
debt	3	3)
since	3	_
early	3	(16
last	3	_
year	3	16)
.	3	_
``	3	_
Argentina	3	(1)
aspires	3	_
to	3	_
reach	3	_
a	3	(17
reduction	3	_
of	3	_
50	3	(6
%	3	_
in	3	_
the	3	(18
value	3	_
of	3	_
its	3	(3|(1)
external	3	_
debt	3	17)|6)|18)|3)
,	3	_
``	3	_
Mr.	3	(2
Rapanelli	3	2)
said	3	_
through	3	_
his	3	(2)|(19|(20
spokesman	3	20)
,	3	_
Miguel	3	_
Alurralde	3	19)
.	3	_
Mr.	4	(2
Rapanelli	4	2)
met	4	_
in	4	_
August	4	(21)
with	4	_
U.S.	4	(22|(23)
Assistant	4	(24
Treasury	4	_
Secretary	4	24)
David	4	_
Mulford	4	22)
.	4	_
Argentine	5	(25|(26|(1)
negotiator	5	26)
Carlos	5	_
Carballo	5	25)
was	5	_
in	5	_
Washington	5	(27)|(28
and	5	_
New	5	(29
York	5	28)|29)
this	5	(30
week	5	30)
to	5	_
meet	5	_
with	5	_
banks	5	(4)
.	5	_
Mr.	6	(2
Rapanelli	6	2)
recently	6	_
has	6	_
said	6	_
the	6	(31
government	6	_
of	6	_
President	6	(5
Carlos	6	_
Menem	6	_
,	6	_
who	6	(5)
took	6	_
office	6	(32)
July	6	(33
8	6	31)|5)|33)
,	6	_
feels	6	_
a	6	(34
significant	6	_
reduction	6	_
of	6	_
principal	6	(35|(36)
and	6	_
interest	6	34)|35)|(37)
is	6	_
the	6	(38
only	6	_
way	6	_
the	6	(39
debt	6	(3)
problem	6	38)|39)
may	6	_
be	6	_
solved	6	_
.	6	_
But	7	_
he	7	(2)
has	7	_
not	7	_
said	7	_
before	7	_
that	7	_
the	7	(1
country	7	1)
wants	7	_
half	7	(6
OF	7	_
the	7	(3
debt	7	6)|3)
forgiven	7	_
.	7	_
#end document vpc_0021
#begin document vpc_0022
.
.
.
```

The rest of the files in that phase (_data/preco.conll_, _data/dev_ARRAU.conll_ and _data/test_ARRAU.conll_ ) have the following simpler format:

```
#begin document vpc_0021
Argentina	(1)
said	_
it	(1)
will	_
ask	_
creditor	(4
banks	4)
to	_
halve	_
its	(1)|(3
foreign	_
debt	_
of	_
$	(7
64	_
billion	_
the	_
in	_
the	(8
developing	_
world	3)|7)|8)
.	_
The	(9
declaration	_
by	_
Economy	(2|(10|(11)
Minister	10)
Nestor	_
Rapanelli	9)|2)
is	_
believed	_
to	_
be	_
the	(12
first	_
time	_
such	(13
an	_
action	13)
has	_
been	_
called	_
for	_
by	_
an	(2
Argentine	(1)
official	_
of	_
such	(14
stature	12)|2)|14)
.	_
The	(1
Latin	(15
American	15)
nation	1)
has	_
paid	_
very	_
little	_
on	_
its	(1)|(3
debt	3)
since	_
early	(16
last	_
year	16)
.	_
``	_
Argentina	(1)
aspires	_
to	_
reach	_
a	(17
reduction	_
of	_
50	(6
%	_
in	_
the	(18
value	_
of	_
its	(3|(1)
external	_
debt	17)|6)|18)|3)
,	_
``	_
Mr.	(2
Rapanelli	2)
said	_
through	_
his	(2)|(19|(20
spokesman	20)
,	_
Miguel	_
Alurralde	19)
.	_
Mr.	(2
Rapanelli	2)
met	_
in	_
August	(21)
with	_
U.S.	(22|(23)
Assistant	(24
Treasury	_
Secretary	24)
David	_
Mulford	22)
.	_
Argentine	(25|(26|(1)
negotiator	26)
Carlos	_
Carballo	25)
was	_
in	_
Washington	(27)|(28
and	_
New	(29
York	28)|29)
this	(30
week	30)
to	_
meet	_
with	_
banks	(4)
.	_
Mr.	(2
Rapanelli	2)
recently	_
has	_
said	_
the	(31
government	_
of	_
President	(5
Carlos	_
Menem	_
,	_
who	(5)
took	_
office	(32)
July	(33
8	31)|5)|33)
,	_
feels	_
a	(34
significant	_
reduction	_
of	_
principal	(35|(36)
and	_
interest	34)|35)|(37)
is	_
the	(38
only	_
way	_
the	(39
debt	(3)
problem	38)|39)
may	_
be	_
solved	_
.	_
But	_
he	(2)
has	_
not	_
said	_
before	_
that	_
the	(1
country	1)
wants	_
half	(6
OF	_
the	(3
debt	6)|3)
forgiven	_
.	_
#end document vpc_0021
#begin document vpc_0022
.
.
.
```

to generate the dataset in the first format for train_ARRAU_sen.conll, apart of changing IO filenames, you might also need to uncomment L106 & L109 and comment L107 & L110 in the mmax2conll.py script. 

Sorry for the mess, I did those scripts at early development, and as once obtained the corpora on the raw format I needed I didn't check much those files. 

If I didn't explain something properly, or you have any other questions about this or later command calls, fell free to reply here or open a new issue and I will try to do my best to help.

Regards,

Gorka

**Comment by hienvuhuy** [comment]
Thanks for your explanation. 
Sorry for not responding to you soon. 
Can you tell me about the file "word2doc.py"? I found it on your Readme.MD file, but I don't know where it is.
Thanks for your support and sorry for replying late.

**Comment by hienvuhuy** [comment]
And if possible, could you explain the files "BPE/en_raw.txt" and "BPE/en16k.bpe"?
Is the file "BPE/en16k.bpe" similar to "en16k.bpe" in your provided code? and how could I get the file "BPE/en_raw.txt"?

**Comment by GorkaUrbizu** [comment]
> 
> 
> And if possible, could you explain the files "BPE/en_raw.txt" and "BPE/en16k.bpe"? Is the file "BPE/en16k.bpe" similar to "en16k.bpe" in your provided code? and how could I get the file "BPE/en_raw.txt"?

Hi @hienvuhuy ! and thank you for your interest in my work again.

"BPE/en_raw.txt" was the English raw test I used to train the BPE model. For this I think that I used the test extracted from ARRAU and PreCo datasets. I can't provide that file as I can't share those datasets due to their licenses, but if you already got those datasets, it should be easy to extract all the words in a txt file. Otherwise. if you use any other English raw text source (Wikipedia, news, ... better if you have at least 1-10M tokens) you should get similar results (or even better =P).

"BPE/en16k.bpe" and "en16k.bpe" are the same files. just that I changed the structure of the directories (My bad, I will correct the README )

About "en16k.bpe", it's the output of the BPE subword vocabulary I trained from "BPE/en_raw.txt". So if you take that (ready to use) file for the following steps in the README file, you can skip training it (so no need to obtain or create the text file "BPE/en_raw.txt")

Feel free to ask if there is something I didn't explain well enough.

Gorka

**Comment by GorkaUrbizu** [comment]
> 
> 
> Thanks for your explanation. Sorry for not responding to you soon. Can you tell me about the file "word2doc.py"? I found it on your Readme.MD file, but I don't know where it is. Thanks for your support and sorry for replying late.

Yep, that file is missing. 

It does the same as word2seq.py, but instead of creating instances of different lengths of sequences and with duplicated parts, it creates a single instance for each document. That why we can evaluate our neural model on the whole documents.

I will try to find that missing file, and upload it. I will reply here when I do so. I should be able to do it for this Friday the latest.

Gorka

**Comment by hienvuhuy** [comment]
Hi, did you find this file? 
If not, can you simply write a small description for it?

Thanks.

**Comment by GorkaUrbizu** [comment]
> Hi, did you find this file? If not, can you simply write a small description for it?
> 
> Thanks.

Sorry about that.
I didn't have time to search for it yet. I will try to do it this week. Wednesday/Thursday most probably.

**Comment by hienvuhuy** [comment]
Thanks

**Comment by GorkaUrbizu** [comment]
> Hi, did you find this file? If not, can you simply write a small description for it?
> 
> Thanks.

I uploaded it to the repository. 
I hope you have everything you need to run this work.

**Comment by hienvuhuy** [comment]
Thank you very much.
